joy_manager:
  topic: /cmd_vel
  type: Twist
  publish_multiple_halt: false
  throttle:
    lin_increment: 0.25
    lin_throttle_ctrl: DPAD_VERT
    ang_increment: 0.25
    ang_throttle_ctrl: DPAD_HORIZ
  turbo: 0
  data:
    linear:
      x: LEFT_JOY_VERT
      y: 0
      z: 0
    angular:
      x: 0
      y: RIGHT_JOY_VERT
      z: RIGHT_JOY_HORIZ
soft_estop_trigger:
  topic: /soft_estop/trigger
  type: Bool
  button: B
soft_estop_reset:
  topic: /soft_estop/reset
  type: Bool
  button: Y
